### ISSUE TITLE
Crash after adding your mod.

### ISSUE THREAD

**Issue by dopa2077** [Su5eD/AdvMachinesPatch#1]
Something funny is going on when i add your mod to my modpack...

https://pastebin.com/gmMDkwTw

**Comment by Su5eD** [comment]
> mods.su5ed.advsolarpatch.PluginModContainer.getModMetadata(PluginModContainer.java:31)

Uhh, not sure if this is the right mod

Anyway, I've already pushed a fix for this in AdvSolarPatch. Can you try using the latest (1.2.1) version?

**Comment by dopa2077** [comment]
Using the latest version (1.2.1) the game crash immediately after pressing play (no crash report) ... the problem is when i added "Advanced Machines Patcher" (1.0) the game crash resulting the crash report from above. (every time)

Solar patcher (1.2) works perfectly without advance machines patcher.

**Comment by dopa2077** [comment]
the problem seem to be fix now, thanks.
