### ISSUE TITLE
[Bug] Thermal Washer

### ISSUE THREAD

**Issue by Romz24** [Su5eD/AdvMachinesPatch#2]
1. It requires Sulfur Dust to craft instead of ore:dustSulfur. When you use the UniDict mod, you cannot craft this mechanism
2. The machine interface has a broken texture
![image](https://user-images.githubusercontent.com/2458113/219074510-a0cf2cdd-ad7a-4301-b71d-22817f5a6290.png)

**Comment by Su5eD** [comment]
I'll fix the issue with sulfur dust, although I can't reproduce the texture glitch using latest Advanced Machines.
![Thermal Washer](https://user-images.githubusercontent.com/51261569/219129815-41b42f4c-c2dc-4f7d-8a3f-f99874ff6e15.png)
